name: Practice challenge
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest # Runner (server)
        steps:
            - name: Get code
              uses: actions/checkout@v5
            - name: Install dependencies
              run: npm ci # install dependencies that are in the package.json file
            - name: Lint
              run: npm run lint
            - name: Test code
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy code
              run: echo "Deploying"